name: Windows RDP with Serveo and Software Installation
on:
  workflow_dispatch:
jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 hours
    steps:
      - name: Initialize Setup Directory
        run: |
          Write-Output "Initializing environment for RDP and software setup"
          New-Item -ItemType Directory -Path "C:\RDPServeo" -Force
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "ServeoRDP2025!" -Force)
          Write-Output "RDP configured with username: runneradmin, password: ServeoRDP2025!"
      - name: Install Google Chrome
        run: |
          $chromeUrl = "https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B00000000-0000-0000-0000-000000000000%7D%26lang%3Den%26browser%3D4%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dtrue%26ap%3Dx64-stable-statsdef_1%26brand%3DGCEA/dl/chrome/install/GoogleChromeStandaloneEnterprise64.msi"
          Invoke-WebRequest $chromeUrl -OutFile C:\RDPServeo\ChromeInstaller.msi
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i C:\RDPServeo\ChromeInstaller.msi /quiet /norestart" -Wait
          Write-Output "Google Chrome installed successfully"
        continue-on-error: true
      - name: Install Python
        run: |
          Invoke-WebRequest https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe -OutFile C:\RDPServeo\python-installer.exe
          Start-Process -FilePath C:\RDPServeo\python-installer.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait
          Write-Output "Python 3.12 installed successfully"
        continue-on-error: true
      - name: Install Visual Studio Code
        run: |
          Invoke-WebRequest https://update.code.visualstudio.com/latest/win32-x64-user/stable -OutFile C:\RDPServeo\VSCodeSetup.exe
          Start-Process -FilePath C:\RDPServeo\VSCodeSetup.exe -ArgumentList "/VERYSILENT /MERGETASKS=!runcode" -Wait
          Write-Output "Visual Studio Code installed successfully"
        continue-on-error: true
      - name: Start Serveo Tunnel
        run: |
          $subdomain = "rdp-$(New-Guid)".Replace('-','')
          Write-Output "Starting Serveo tunnel with subdomain: $subdomain"
          $sshCommand = "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -R ${subdomain}:80:localhost:3389 serveo.net > C:\RDPServeo\serveo.log 2>&1"
          Start-Process -FilePath "powershell" -ArgumentList "-Command", $sshCommand -NoNewWindow
          Write-Output "Serveo tunnel initiated, logging to C:\RDPServeo\serveo.log"
      - name: Wait and Retrieve Serveo Tunnel URL
        run: |
          $maxAttempts = 10
          $attempt = 1
          $tunnelUrl = $null
          while ($attempt -le $maxAttempts -and $null -eq $tunnelUrl) {
            Write-Output "Attempt $attempt of $maxAttempts to retrieve Serveo tunnel URL..."
            Start-Sleep -Seconds 20
            try {
              $logContent = Get-Content -Path C:\RDPServeo\serveo.log -Raw
              if ($logContent -match "Forwarding.*https://([a-z0-9-]+)\.serveo\.net") {
                $tunnelUrl = $matches[1] + ".serveo.net:3389"
                Write-Output "Serveo tunnel URL found: $tunnelUrl"
              } else {
                throw "Tunnel URL not found in log"
              }
            } catch {
              Write-Output "Failed to retrieve tunnel: $_"
              Get-Content -Path C:\RDPServeo\serveo.log | Select-Object -Last 10
              $attempt++
              if ($attempt -gt $maxAttempts) {
                Write-Output "Max attempts reached. Serveo tunnel failed to initialize. Final log output:"
                Get-Content -Path C:\RDPServeo\serveo.log
                exit 1
              }
            }
          }
          if ($tunnelUrl) {
            echo "RDP_CONNECTION_URL=$tunnelUrl" >> $env:GITHUB_ENV
            echo "RDP Credentials:"
            echo "Username: runneradmin"
            echo "Password: ServeoRDP2025!"
            echo "Connect using an RDP client to: $tunnelUrl"
            echo "Example: In Microsoft Remote Desktop, enter '$tunnelUrl' as the PC name."
          } else {
            Write-Output "Failed to retrieve tunnel URL after $maxAttempts attempts."
            exit 1
          }
      - name: Verify Software Installation
        run: |
          try { python --version } catch { Write-Output "Python verification failed" }
          try { code --version } catch { Write-Output "VS Code verification failed" }
          try { & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version } catch { Write-Output "Chrome verification failed" }
      - name: Keep Workflow Active
        run: |
          Start-Sleep -Seconds 21600 # 6 hours
