name: Windows RDP 6hrs Free

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 hours

    steps:
    - name: Download LocalXpose
      run: |
        Invoke-WebRequest https://lxp-download.sgp1.digitaloceanspaces.com/localxpose.zip -OutFile localxpose.zip
        Expand-Archive localxpose.zip -DestinationPath .

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        net user runneradmin YourSecurePassword123

    - name: Install Chrome, Python, VS Code
      run: |
        choco install googlechrome -y
        choco install python -y
        choco install vscode -y

    - name: Start LocalXpose Tunnel
      run: |
        .\localxpose\loclx.exe tunnel tcp --port 3389 > tunnel.txt 2>&1 &
        timeout /t 15
        type tunnel.txt

    - name: Show RDP Login Info
      run: |
        echo =====================================
        echo RDP Username: runneradmin
        echo RDP Password: YourSecurePassword123
        echo Copy the TCP address above and use it in RDP client.
        echo Example: If you see tcp://0.tcp.ngrok-free.app:12345 use:
        echo Host: 0.tcp.ngrok-free.app
        echo Port: 12345
        echo =====================================
        timeout /t 21600
