name: Free Windows RDP (6 Hours, Show Full Details)

on:
  workflow_dispatch:

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP & Set Password
      shell: pwsh
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 1
        net user runneradmin RDPpassword123!

    - name: Install Chrome, Python, VS Code, LocalXpose
      shell: pwsh
      run: |
        choco install googlechrome -y
        choco install python -y
        choco install vscode -y
        choco install localxpose -y

    - name: Start LocalXpose Tunnel and Show Details
      shell: pwsh
      run: |
        Write-Host "Starting LocalXpose tunnel on port 3389 (RDP)..."

        $job = Start-Job { loclx tunnel tcp --port 3389 --region eu }
        Start-Sleep -Seconds 15
        $output = Receive-Job $job -Wait

        # Extract tcp:// line
        $tcpLine = $output | Where-Object { $_ -match "^tcp://.*:\d+$" }

        if (-not $tcpLine) {
          Write-Error "Could not find TCP tunnel address in output!"
          exit 1
        }

        # Parse host and port
        $tcpLine = $tcpLine.Trim()
        $tcpLine = $tcpLine -replace "^tcp://", ""
        $parts = $tcpLine.Split(":")

        $host = $parts[0]
        $port = $parts[1]

        Write-Host ""
        Write-Host "======================================="
        Write-Host "           RDP CONNECTION DETAILS"
        Write-Host "======================================="
        Write-Host "Host:     $host"
        Write-Host "Port:     $port"
        Write-Host "Username: runneradmin"
        Write-Host "Password: RDPpassword123!"
        Write-Host "======================================="
        Write-Host "Copy these details into your RDP client."
        Write-Host "Tunnel will stay active for 6 hours."
        Write-Host "======================================="

        Start-Sleep -Seconds 21600
