name: Free Windows RDP (6 Hours, LocalXpose)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 hours

    steps:
    - name: Download LocalXpose
      run: |
        Invoke-WebRequest https://lxp-download.sgp1.digitaloceanspaces.com/localxpose.zip -OutFile localxpose.zip
        Expand-Archive localxpose.zip -DestinationPath C:\localxpose

    - name: Enable RDP & Set Password
      run: |
        # Enable RDP connections
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
        # Set password for runneradmin
        net user runneradmin RDPpassword123!

    - name: Install Chrome, Python, VS Code
      run: |
        choco install googlechrome -y
        choco install python -y
        choco install vscode -y

    - name: Start LocalXpose Tunnel
      run: |
        cd C:\localxpose
        cmd /c start /b loclx.exe tunnel tcp --port 3389 --region eu > C:\tunnel.txt 2>&1
        timeout /t 15
        type C:\tunnel.txt

    - name: Extract Tunnel Info
      run: |
        findstr /C:"tcp://" C:\tunnel.txt > C:\public_address.txt
        echo =========================================
        echo    WINDOWS RDP DETAILS
        echo =========================================
        for /f "tokens=* delims=" %%A in (C:\public_address.txt) do (
            set ADDR=%%A
            setlocal enabledelayedexpansion
            set ADDR=!ADDR:tcp://=!
            echo RDP Address: !ADDR!
            endlocal
        )
        echo Username: runneradmin
        echo Password: RDPpassword123!
        echo =========================================
        echo COPY THE ABOVE INFO INTO YOUR RDP CLIENT
        echo SESSION WILL LAST FOR 6 HOURS
        echo =========================================
      shell: cmd

    - name: Keep Session Alive
      run: timeout /t 21600
