name: Free Windows RDP (6 Hours, Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 hours

    steps:
    - name: Enable RDP & Set Password
      run: |
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
        # Set password for RDP login
        net user runneradmin RDPpassword123!

    - name: Install Chrome, Python, VS Code, LocalXpose
      run: |
        choco install googlechrome -y
        choco install python -y
        choco install vscode -y
        choco install localxpose -y

    - name: Start LocalXpose TCP Tunnel
      run: |
        # Start tunnel to RDP (port 3389)
        loclx tunnel tcp --port 3389 --region eu > C:\tunnel.txt 2>&1 &
        timeout /t 15
        type C:\tunnel.txt

    - name: Show RDP Connection Info
      run: |
        echo =========================================
        echo   WINDOWS RDP DETAILS
        echo =========================================
        for /f "tokens=* delims=" %%A in (C:\tunnel.txt) do (
            echo %%A | findstr /C:"tcp://"
        )
        echo Username: runneradmin
        echo Password: RDPpassword123!
        echo =========================================
        echo COPY ABOVE INFO INTO YOUR RDP CLIENT
        echo SESSION WILL LAST FOR 6 HOURS
        echo =========================================
      shell: cmd

    - name: Keep RDP Session Alive
      run: timeout /t 21600
