name: Free Windows RDP (6 Hours, Fixed & Working)

on:
  workflow_dispatch:

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 hours max runtime

    steps:
    - name: Enable RDP & Set Password
      shell: pwsh
      run: |
        # Enable RDP connections
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name 'UserAuthentication' -Value 1

        # Set password for RDP user 'runneradmin'
        net user runneradmin RDPpassword123!

    - name: Install Chrome, Python, VS Code, LocalXpose
      shell: pwsh
      run: |
        choco install googlechrome -y
        choco install python -y
        choco install vscode -y
        choco install localxpose -y

    - name: Start LocalXpose Tunnel and Keep Alive
      shell: pwsh
      run: |
        Write-Host "Starting LocalXpose tunnel on port 3389 (RDP)..."

        # Start LocalXpose tunnel in a background job
        $job = Start-Job { loclx tunnel tcp --port 3389 --region eu }
        Start-Sleep -Seconds 15

        # Capture and print tunnel info from the job output
        $output = Receive-Job $job -Wait
        foreach ($line in $output) {
          if ($line -match "tcp://") {
            Write-Host "RDP Tunnel Address: $line"
          }
        }

        Write-Host "RDP Username: runneradmin"
        Write-Host "RDP Password: RDPpassword123!"
        Write-Host "Tunnel will stay active for 6 hours."

        # Keep the job and tunnel alive for 6 hours
        Start-Sleep -Seconds 21600
